version: '3.8'

services:

  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    container_name: client-app
    ports:
      - '3003:3003'
    networks:
      - client
    env_file:
      - '.env'

  nginx:
    image: nginx:stable-alpine
    ports:
      - '3008:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    networks:
      - client

networks:
  client:
